### GET ALL EVENTS
GET http://localhost:8080/event/all
Content-Type: application/json
### GET EVENT BY ID
GET http://localhost:8080/event/b34bjsakmad
Content-Type: application/json
### GET ALL PRICES
GET http://localhost:8080/price/all
Content-Type: application/json
### GET ALL PLACES
GET http://localhost:8080/place/all
Content-Type: application/json
### GET ALL USERS
GET http://localhost:8081/user/all
Content-Type: application/json
### GET USER BY ID
GET http://localhost:8080/user/3
Content-Type: application/json
###