### GET ALL EVENTS
GET https://dziesiedziejev2.herokuapp.com/event/all
Content-Type: application/json
### GET EVENT BY ID
GET http://dziesiedziejev2.herokuapp.com/event/b34bjsakmad
Content-Type: application/json
### GET ALL PRICES
GET http://dziesiedziejev2.herokuapp.com/price/all
Content-Type: application/json
### GET ALL PLACES
GET http://dziesiedziejev2.herokuapp.com/place/all
Content-Type: application/json
### GET ALL USERS
GET http://dziesiedziejev2.herokuapp.com/user/all
Content-Type: application/json
### GET USER BY ID
GET http://dziesiedziejev2.herokuapp.com/user/3
Content-Type: application/json
###